name: package

on:
  schedule:
    - cron: '0 18 * * *'

defaults:
  run:
    shell: bash

jobs:
  package:
    name: build package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
          # - centos6
          - centos7
          - centos8
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: package
        run: ./package/package.sh
      - name: output some vars
        id: vars
        env:
          SHA_EXT: sha256sum.txt
        run: |
          filename=$(find pkg-build/cpack_output -type f \( -iname \*.deb -o -iname \*.rpm \))
          sha256sum $filename > $filename.$SHA_EXT
          subdir=$(date -u +%Y.%m.%d)
          echo "::set-output name=filepath::$filename"
          echo "::set-output name=shafilepath::$filename.$SHA_EXT"
          echo "::set-output name=subdir::$subdir"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-v2-nightly
<<<<<<< HEAD
          path: build/cpack_output
      - name: upload package to oss
        uses: tvrcgo/upload-to-oss@v0.3.0
=======
          path: pkg-build/cpack_output
      - uses: ./.github/actions/upload-to-oss-action
>>>>>>> ca21bad9... Rename build directory of packaging to pkg-build (#896)
        with:
          key-id: ${{ secrets.OSS_ID }}
          key-secret: ${{ secrets.OSS_SECRET }}
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          bucket: nebula-graph
<<<<<<< HEAD
          asset-path: build/cpack_output
          target-path: /package/v2-nightly/${{ steps.vars.outputs.subdir }}
=======
          asset-path: pkg-build/cpack_output
          target-path: package/v2-nightly/${{ steps.vars.outputs.subdir }}
>>>>>>> ca21bad9... Rename build directory of packaging to pkg-build (#896)
